import {environment} from "../../environments/environment";

export const API_ENDPOINT = {
  auth: {
    login: `${environment.API_URL}/auth/login`,
    logout: `${environment.API_URL}/auth/logout`,
    refresh: `${environment.API_URL}/auth/refresh`,
    register: `${environment.API_URL}/auth/signup`,
    switchRole: `${environment.API_URL}/auth/switch-role`,
    assignRoles: `${environment.API_URL}/auth/users`,
  },
  referenceData: `${environment.API_URL}/reference-data`,
  internalReferenceData: `${environment.API_URL}/internal-reference-data`,
  divisionSettings: `${environment.API_URL}/division-settings`,
  pillarConfigs: `${environment.API_URL}/pillar-configs`,
  aip: `${environment.API_URL}/aips`,
  schoolNeed: `${environment.API_URL}/school-needs`,
  schools: `${environment.API_URL}/schools`,
  upload: `${environment.API_URL}/upload`,
  users: {
    profile: `${environment.API_URL}/users/profile`,
    changePassword: `${environment.API_URL}/users/change-password`,
    list: `${environment.API_URL}/users`,
    rolesSubordinates: `${environment.API_URL}/users/roles/subordinates`,
  },
  userInvites: `${environment.API_URL}/user-invites`,
  engagements: `${environment.API_URL}/engagements`,
  stakeholderProfiles: `${environment.API_URL}/stakeholder-profiles`,
  mail: {
    confirmEmail: `${environment.API_URL}/mail/confirm-email`,
    confirmEmailVerify: `${environment.API_URL}/mail/confirm-email/verify`,
    resetPassword: `${environment.API_URL}/mail/reset-password`,
    resetPasswordVerify: `${environment.API_URL}/mail/reset-password/verify`,
    invite: `${environment.API_URL}/mail/invite`,
  },
  reports: `${environment.API_URL}/reports`,
  ppaPlan: `${environment.API_URL}/ppa-plan`,
  activity: `${environment.API_URL}/activity`,
  offices: `${environment.API_URL}/offices`,
  announcements: `${environment.API_URL}/announcements`,
  openrouter: `${environment.API_URL}/openrouter`,
  widget: {
    resourceGenerations: `${environment.API_URL}/widgets/resource-generations`,
    partners: `${environment.API_URL}/widgets/partners`,
    aipStatusStats: `${environment.API_URL}/widgets/aip-status-stats`,
    visitorCount: `${environment.API_URL}/widgets/visitor-count`,
    visitorCountHit: `${environment.API_URL}/widgets/visitor-count/hit`,
    visitorActiveCount: `${environment.API_URL}/widgets/visitor-count/active`,
    visitorActiveHeartbeat: `${environment.API_URL}/widgets/visitor-count/active/heartbeat`,
  },
}
